### ISSUE TITLE
This crashes ciderpress 4.x

### ISSUE THREAD

**Issue by Keatah** [fadden/ciderpress#20]
ftp://ftp.apple.asimov.com/pub/apple_II/images/communications/proterm/mousetrap.shk

Trying to open that file causes an unrecoverable crash. Have to manually terminate ciderpress. However, CP version 3.x reads it just fine.

**Comment by fadden** [comment]
The failure happens because `NufxArchive::DateTimeToSeconds()` is getting passed a bogus NuDateTime value (hour=255), which it passes on to the Windows CTime constructor.  CTime throws an exception (`ATLENSURE( nHour >= 0 && nHour <= 23 );`), which then makes everybody unhappy to a surprising degree.

I don't think the difference in behavior between different versions of CP is dependent on code in CP.  I think we're either linking against a different version of the Windows library, or something changed in the way exception handling works.  Whatever the case, passing a bad argument to CTime seems to be fatal, so we'll need to stop doing that.

**Comment by fadden** [comment]
Fixed in release v4.0.2-a3.

**Comment by fadden** [comment]
There's a bunch of comments at the top of atldef.h that finish with:

> So we've done a broad replace of all the member-related ATLASSERT to ATLASSUME.

`ATLASSERT` and `ATLASSUME` both cause a debug break when a problem is noticed. The difference is that `ATLASSUME` throws a C++ exception in a release build, while `ATLASSERT` does nothing at all.  This resulted in the change in behavior vs. the older CP.

CiderPress and its various libraries are generally unaware of exceptions.  Not sure why that resulted in the program hanging.
