### ISSUE TITLE
Reading and writing to real 3.5" disks in Windows.

### ISSUE THREAD

**Issue by scottie-uk** [fadden/ciderpress#21]
Dear Developers,
                           I want to use cider press to write disk images to a real 3.5" floppy disk so I can use them on my Applie //C+. Your documentation does mention physical disks (hard disks I presume) and CF drives, but is very vague in providing instructions on how to write to and read from real 3.5"physical floppy disks (blank disks for apple IIC+ not HD disks) via physical PCs floppy disk drive.

If this is not something CiderPress is designed to do, be more upfront about this in your documentation, especially places like the about section and FAQ.

If it is something Cider Press supports, make better documentation or make it easier for users to find this information. Certainly, if it is possible your user interface does not make this apparent either.

           Kind Regards,

                      Andrew.

**Comment by fadden** [comment]
In the CiderPress help (launch app, hit F1), open "Appendix", then "About Removable Media (CF, floppy, CD-ROM, external HD)".  The section explains what will and won't work.  For example:

> CiderPress has been tested with 720KB and 1.4MB 3.5" floppy disks.  It will not work with 800K or 1.6MB 3.5" floppies from an Apple II or Macintosh, because the drive in a PC is not capable of reading them.

**Comment by scottie-uk** [comment]
Thanks for the response. I think you could expand on that a little and put it more up front n the FAQ, Many folks who are new to the CiderPress tool might think that because the format is physically the same that it should be compatible and that your software will do it. It might also be worth updating that very first paragraph under "What Is CiderPress", that the software manages images  but does not support the reading and writing of physical apple II disks using hardware.. Burying this info in an appendix, makes this information hard to find and less than effective.

I've done further research on this, and the stopping point is the firmware of a PCs floppy drive, it's just different and can't be made to work with Apple disks.  However, there is a hardware device called a [CatWeisel, ](https://en.wikipedia.org/wiki/Individual_Computers_Catweasel) that originated in the 90's and does allow a PCs floppy to interface with other formats. Maybe that would work with the IIC disks.

**Comment by fadden** [comment]
From the a2ciderpress.com page, under "key features", click on "Direct access to hard drives, removable media, and CF cards". It says:

 * Read and write ProDOS-formatted 720KB and 1.4MB floppy disks. [...] [Works for PC-format disks.  Does not work with Apple-format 800KB and 1.6MB disks, nor 140KB 5.25" disks.]

The FAQ has a question "How do I transfer my Apple II disks to my PC?"; the answer includes:

 * While CiderPress supports ProDOS-formatted 720KB and 1.4MB 3.5" floppy disks, it cannot support 800KB 3.5" disks or 140K 5.25" disks due to limitations of the disk drives used on PCs.

Your best bet for transferring disks is probably [ADTPro](http://adtpro.sourceforge.net/).
