### ISSUE TITLE
Feature Request: Retain (or Change) Volume Name when Restoring a Volume

### ISSUE THREAD

**Issue by mmmann** [fadden/ciderpress#23]
I noticed that copying entire volumes (from a *.po file) also overwrites the partition name. Could that be an option? I want the contents of the partition (e.g. the games partition from whatisthe2gs.com), but I prefer my partition name, "GAMES," than the author's original partition name, "G."

Thank you for your consideration and for all of the dedication and hard work in providing this amazing utility to the Apple II community.

**Comment by fadden** [comment]
Partition names are a thing in some cases but not others, e.g. MacPartition volumes have a space for them but CFFA volumes are just one ProDOS volume after another.  I didn't think I edited anything in the MacPart header when importing an image, but it's been 10 years.  My guess would be that the partition name is unchanged but CiderPress is choosing to show the ProDOS volume names rather than the partition names, because not all formats support explicit partition naming.

(One way to tell: Tools > Disk Sector Viewer, open the MacPart volume or image file, and look at the first few blocks... there's one partition per block starting from block 1.  See if your original partition names are still present.)

You can use Actions > Rename Volume to change the ProDOS volume name.

**Comment by fadden** [comment]
FWIW, CiderPress II shows both the APM partition names and the filesystem volume names.
