### ISSUE TITLE
Virus in ciderpress.exe??

### ISSUE THREAD

**Issue by BrianPeek** [fadden/ciderpress#29]
Just tired to pull the 4.0.3 release from the Releases tab above and install, and I'm getting Defender popping up telling me there's a virus in ciderpress.exe .  False positive?  Anyone else seeing this?

**Comment by fadden** [comment]
I've heard of anti-virus warnings firing before.  They seem to be false-positives, e.g. https://groups.google.com/d/msg/comp.sys.apple2/10GviIxnocs/yapDDwNsAQAJ

I'm using Windows Defender on Win10, and it has never complained.  Nor has Malwarebytes.  Yours is the first complaint I've heard since 4.0.3 was released.

**Comment by BrianPeek** [comment]
It does seem bogus.  Here's the warning from defender:  
![image](https://user-images.githubusercontent.com/2321675/35754979-7c61f4e4-0833-11e8-8418-d40ab95d91cd.png)

And here's a scan from VirusTotal:

https://www.virustotal.com/#/file/c21bc3e17479810adc56c765b9b302a73ffff3410eb0408cf7d3d8601bd1eb43/detection

![image](https://user-images.githubusercontent.com/2321675/35754989-8ea4b8bc-0833-11e8-94b8-0d7a35ab35b8.png)

<shrug> Anyway, I went through the hassle of building my own and updating the projects to VS2017 so maybe that's useful to someone.  I submitted a PR.

Regardless, thanks for maintaining this app!  :)
