### ISSUE TITLE
Unable to install 4 PRODOS Images to a Transcend 128MB Industrial SD Card

### ISSUE THREAD

**Issue by tokabln** [fadden/ciderpress#31]
Dear folks,

I'm having trouble using Ciderpress v4.0.3 or v3.0.1 together with a 128MB Transcend Industrial SD Card.
Using the "Volume copier" functionallity and trying to install a ProDOS 32MB image to an empty card, always leads into the problem that this image will consume the full 128MB of the card instead of creating one 32MB image and leaving room for additional 3 CFFA 32MB images. Ciderpress doesn't offer CFFA (4 or 6 patition) filesystem here.

![volume copier 1](https://user-images.githubusercontent.com/36958267/36847037-45d430ba-1d5d-11e8-8ace-c3c8055f371f.JPG)
![volume copier 2](https://user-images.githubusercontent.com/36958267/36847038-45f953ae-1d5d-11e8-8378-243d79c2ae9e.JPG)
![volume copier 3](https://user-images.githubusercontent.com/36958267/36847039-461e7792-1d5d-11e8-8f56-44aaebbab821.JPG)
![volume copier 4](https://user-images.githubusercontent.com/36958267/36847040-46433348-1d5d-11e8-9d8b-90970f6ada54.JPG)
![volume copier 5_prodos](https://user-images.githubusercontent.com/36958267/36847041-466764b6-1d5d-11e8-8ef5-49c91c4ef1ec.JPG)
![volume copier 6](https://user-images.githubusercontent.com/36958267/36847042-46895238-1d5d-11e8-9458-9bcf7f583352.JPG)

Using a 512MB card everything works fine, means Ciderpress offers CFFA (4 or 6 partions) filesystem capability automatically.

![volume copier 7 - 512mb cffa offer](https://user-images.githubusercontent.com/36958267/36847307-27d2cec2-1d5e-11e8-943a-87c9caf47d49.JPG)

So it seems to be that the conflict only appears when using a 128MB SD card. Can you take a look into this, please ?

Kind regards Torsten

**Comment by fadden** [comment]
CFFA volumes have no explicit partitioning. CiderPress tries to guess at what it's supposed to be.  This gets tricky when it might be a CFFA image with only one valid volume, or might be a disk image file with a bunch of empty space at the end.

CiderPress is failing to recognize the "128MB" card because it's actually 121MB, which isn't big enough for four full partitions.  This causes the "4 or 6 partition" test to bail out.

For example, here are two mostly-empty disk images with the same block count as yours.  The one with two formatted partitions is recognized as CFFA, while the one with only one formatted partition is recognized as an oversized ProDOS volume: [CFFA-121MB.zip](https://github.com/fadden/ciderpress/files/1772254/CFFA-121MB.zip)

Ideally the format override dialog would allow you specify that this should be handled as a CFFA volume, but that currently doesn't work.

**Comment by tokabln** [comment]
Hi Andy,

many thanks for your kind explanation. There's a question left than if it will be possible to enhance Ciderpress to allow three 32MB images in the future? 

It's just a question.

Kind regards Torsten
(torsten.kapke@snafu.de)

**Comment by fadden** [comment]
It supports them.  It just doesn't recognize it for what it is until the partitions get formatted.

For example, you should be able to copy the CFFA-121MB-2p.po image from the zip file I attached earlier onto your SD card and be able to access three 32MB volumes and one 25MB volume.  So long as there are at least two recognizable volumes you're good to go.  The problem is that CiderPress doesn't provide a way to create that second volume, so you're kind of stuck unless you have 3rd-party software that can create a multi-volume image of a specific size.

**Comment by tokabln** [comment]
Ah... okay, understand. 

Thanks

Kind regards Torsten
(torsten.kapke@snafu.de)
