### ISSUE TITLE
CiderPress crashes with "Assertion failed!" when trying to add files to a disk image

### ISSUE THREAD

**Issue by robinhood2014** [fadden/ciderpress#32]
Here are the full details of the error.
![image](https://user-images.githubusercontent.com/6971466/40592881-acecb4ae-61e9-11e8-9cc9-9ee17ae23bfe.png)
The error seems to happen only with ProDOS disk images. DOS 3.3 disk images don't return this error.

**Comment by fadden** [comment]
Something is going wrong when writing a directory.  Somehow a bad block number (0 or 1) is ending up in the list of blocks used to store the directory.

Can you share the disk image and files for which you are seeing this behavior?  (You can drag & drop them into the bug report, or e-mail them to me if you'd rather they not be public.)  How many files are you adding? Are you adding them to the root directory or a subdirectory?  Are you using the "official" 4.0.3 release executable?

**Comment by robinhood2014** [comment]
In this example, I'll just use an image of the ProDOS User's Disk, but one should be able to duplicate this bug on any ProDOS-formatted disk image. I've enclosed a zip file containing the disk image plus the three files I'm attempting to add to its root directory using CiderPress version 4.0.3.

[ProDOS Users Disk - 680-0224-C.zip](https://github.com/fadden/ciderpress/files/2060689/ProDOS.Users.Disk.-.680-0224-C.zip)

**Comment by fadden** [comment]
It works fine for me:

![success](https://user-images.githubusercontent.com/6185696/40849735-95fbc2a8-6577-11e8-91aa-e97ac93272cc.png)

I successfully booted the disk in AppleWin afterward and ran all three SYS files.  I tried a few different options in the Add Files dialog; no change.

I haven't received any other reports about problems adding files to ProDOS disks.  Could be an uninitialized variable that happens to come up badly for you, but recent versions of Visual Studio seem to do well at spotting those.  The ProDOS code hasn't changed in over three years, so it's not a recent update.

I'm at something of a loss.  Do you have another PC you can try it on?

**Comment by fadden** [comment]
Unable to reproduce.

**Comment by roughana** [comment]
I have experienced this issue today with Ciderpress 4.0.3
I opened this DOS 3.3 image
ftp://ftp.apple.asimov.net/pub/apple_II/images/sound/software_automated_mouth.dsk
I extracted SAM binary file Aux $4000 using preserve Apple II file formats.
It was created in Windows 8 with filename SAM#064000 and has size 16kb

I opened a copy of this ProDOS image (the attempt to add is destructive so keep a backup)
https://github.com/jeremysrand/a2bejwld/releases/download/2.6/a2bejwld.dsk
(I think it has been built with a modern toolchain. So perhaps there could be a bug in their creation process)

I tried to add the SAM#064000 to the root directory, with these options:
-Use file attribute preservation tags
-Include subfolders off - (all misc items turned off)
-Don't convert text files

I receive the exact error as shown in the dialog in OPs issue.

I notice that the icon for adding to the archive is now greyed out, even after reloading, so the attempt has broken the image in some way.

**Comment by fadden** [comment]
CiderPress is incorrectly assuming that the volume directory is 2048 bytes long, and goes looking for 4 blocks of directory data.  The image in question only allocates two blocks to the volume directory, and an assertion fires when CP tries to write the updated volume directory back to disk.

Unfortunately, by that point it has already written the first two blocks, which means there's an entry for a file but the disk block in-use map hasn't been updated.  CP detects that there's a file referencing free blocks, and flags the volume as damaged.

A simple workaround is to copy the files to a ProDOS disk image with a full volume directory.

The fix is to have CP scan the volume dir to determine the actual number of blocks used.  A review of the code suggests that the 4-block assumption isn't made anywhere else; the other places that treat the size as a constant are associated with formatting a new disk.

**Comment by fadden** [comment]
Based on the disk contents, I'd say the a2bejwld.dsk image was made by copying the ProDOS 2.4.2 distribution and deleting most of the files.  The disk image added in the original bug report didn't have this problem.  Judging by the timing and interest in ProDOS utilities, it's possible that the OP was playing with one of the new-fangled ProDOS disks as well.
