### ISSUE TITLE
Volume Copy - Load from file failed with file on share

### ISSUE THREAD

**Issue by inexorabletash** [fadden/ciderpress#33]
Running Ciderpress on a Windows VM, with an HDV file residing on a network share mounted on Z:\, the "Load from file" functionality trying to write to a volume on a CF card hung Ciderpress with no progress then after several minutes crashed (Abort/Retry/Ignore) with some "file not found" error. 

Copying the HDV file to a local drive and retrying worked. 

The HDV file was created directly on the share from Ciderpress, so the other direction works. 

(Apologies for the vague details.)

**Comment by inexorabletash** [comment]
Win7

I should note that the network share is not remote per se: it's provided by the physical machine hosting the VM. Still, there could be a timing issue, or something about how the name is processed.

At some point I'll try to repro, but the failing write effort had trashed the volume on the CF so I was just happy to have found the workaround. If I can get another CF card to play with I'll try again and see if I can find any other clues.

**Comment by fadden** [comment]
At one point I set up a VirtualBox VM with Win7 on it, but unfortunately I don't have a separate key (I'm running Win10 as an upgrade from Win7), so the key activation stuff gets cranky after 30 days.  At least I got the system configured, which is more than I was able to do win WinXP.

The part I don't get is that, if it were going to fail anywhere, I would expect it to fail on the write-to-device side since that's where the "weird" stuff happens.  The read side is just opening a file read-only.

**Comment by inexorabletash** [comment]
Just to make sure we're on the same page, the case which failed for me was "read from HDV file on a share and write to physical CF card", using the "Load from file" option in the UI.

(To me, that would be a "write-to-device" operation, but that would contradict your summary....)

**Comment by fadden** [comment]
I think we're on the same page -- if the write-to-device side were fully broken, your subsequent attempt with a local copy of the file would have failed, which is why I'm assuming it's a read-side problem.  But maybe that's a bad assumption, and it's the *combination* of "read from virtual network" and "write to physical device".  Perhaps having a USB device open for writing interferes with the virtual network?
