### ISSUE TITLE
Feature Request: OMF Support

### ISSUE THREAD

**Issue by dwsJason** [fadden/ciderpress#40]
OMF Supoprt would be really nice!   Maybe you could just give each load segment it's own bank, so they all start at   SEGNUMBER:0000?   I think this would be fine for disassembly purposes.

Just a thought :-)

**Comment by fadden** [comment]
Were you intending this for https://github.com/fadden/6502bench ?

My current plan is to write an "OMF loader" that resolves all of the relocatable stuff, putting each segment into a separate bank as you suggest (probably starting with $02 so we don't tread on any fixed locations).  A SourceGen .dis65 project would be generated that has the mapping of file offsets to addresses in place.

This wouldn't allow you to generate assembly sources that recreated the *original* OMF binary, but I'm not sure that's possible in all cases because of post-processing tools like the one that generates the "fast load" segment.

**Comment by dwsJason** [comment]
Crap, this is in the wrong place.  Isn't parsing the fastload, optional?  Either way, that sounds like an excellent plan.
