### ISSUE TITLE
Feature Request: Drag and drop files between CP windows

### ISSUE THREAD

**Issue by roughana** [fadden/ciderpress#48]
If I want to move files between disk images, I currently have to export from one and import from the other via the filesystem. It would be much more convenient to be able to drag a file or a folder or selection of files/folders from one disk image in a CP window to another disk image in another CP window.

**Comment by fadden** [comment]
You can do it through the clipboard: select the files in CP window # 1, hit Ctrl+C, then move to CP window # 2 and hit Ctrl+V.  (Or open disk image A, copy files, open image B, paste files.)

I vaguely remember drag-and-drop being absurdly complicated in MFC, so I never went near it.

**Comment by fadden** [comment]
This will not be addressed in CiderPress.

I looked at it for https://github.com/fadden/CiderPress2, and it turns out that dragging files in from Windows Explorer is trivially easy to support.  (I actually use it in the demo because, 20 years later, there's still no good "select files and folders" dialog in Windows.)  Dragging between UI elements within the application is straightforward.  Dragging between instances of the application is difficult.  Dragging out to Windows Explorer is tricky, requiring some fancy "virtual file" handling, but there are working examples.  (I think the "to Explorer" and "to other app" are actually going to be the same problem, because you need the receiver to pull the data... if the sender pushes it via the clipboard, you have to read all of the files when the drag starts.)
