### ISSUE TITLE
Feature Request: allow to specify DOS catalog track

### ISSUE THREAD

**Issue by peterferrie** [fadden/ciderpress#68]
I'm porting F-15 Strike Eagle, which is a mostly regular DOS disk, but has its catalog on track $15.  It would be very helpful if CiderPress let me specify the catalog track so that it can extract files from disks like this.

**Comment by fadden** [comment]
This feature needs two things:

 1. A way for the user to tell the application that the catalog track is somewhere else.
 2. A way for the application to tell the filesystem code that it should look somewhere else.

This would be problematic to handle without user intervention, e.g. as an automatic part of filesystem detection, because if a disk has a "dummy" catalog on track $11 then the "hidden" catalog will be totally ignored.

CiderPress II is generally better suited for this, because it supports "raw" DOS files and can preserve DOS sparseness in disk-to-disk copies.  It also has a mechanism for passing application settings into the filesystem code, though that may not be necessary.  From a user-interaction perspective, it has the advantage of not rejecting disk images when the filesystem can't be found.

Approach #&NoBreak;1: add a "try here first" VTOC track/sector setting.  This has global effect, but so long as the auto-detection code tries $11 afterward, standard disks will continue to work.  This would be useful for the command-line tool since it would allow disk-to-disk copies, and only requires setting a couple of numeric options.

Approach #&NoBreak;2: add a "try exactly this filesystem" dialog.  CiderPress has a clumsy escape hatch, enabled by Preferences > Disk Images > Confirm disk image format, that sort of does this.  (It's the only way to see the other half of DOS+ProDOS / DOS+Pascal / DOS+CP/M hybrids.)  CiderPress II could add a button to the disk image info panel that allows overriding the filesystem auto-detection.  For a DOS disk it could take the VTOC track/sector.  Potentially it could allow configuration of the sector codec, for altered addr/data field headers.

Neither version of the CiderPress disk image library currently allows the VTOC track/sector to be overridden, but that's a Simple Matter of Programming.

Of course, if you're in a hurry, there's always the "edit the constant and recompile" approach...
```
File: Asimov/pub/apple_II/images/games/collections/san_inc_dos/F-15 Strike Eagle (san inc crack).dsk
  Filesystem notes:
   I Found 38 unused sectors that are marked used
Disk image (Unadorned, order=dos/sect) - 140KB DOS 3.3 Vol 254, 147 sectors free
Type Auxtyp Modified          Length  Storage *Name                             
---- ------ --------------- -------- -------- ----------------------------------
 B   $0300  [No Date]            206      512 *SIDTRANC.OBJ0
 B   $7800  [No Date]            480      768 *DASH0.MAP
 B   $5208  [No Date]            480      768 *DASH1.MAP
 B   $5208  [No Date]            480      768 *DASH2.MAP
 B   $5208  [No Date]            480      768 *DASH3.MAP
 B   $5208  [No Date]            480      768 *DASH4.MAP
 B   $5208  [No Date]            480      768 *DASH5.MAP
 B   $5208  [No Date]            480      768 *DASH6.MAP
 B   $6200  [No Date]          14096    14592 *SIDTRANC.OBJ1
 B   $1C00  [No Date]            913     1280 *SIDTRANC.OBJ2
 B   $B800  [No Date]           1280     1792 *NIGHT.OBJECTS.OBJ
 B   $6000  [No Date]           1230     1536 *CM
 B   $0201  [No Date]             62      512 *AD
 B   $9000  [No Date]           1024     1536 *EAGLE2.DTA
 B   $999B  [No Date]           7179     7680 *B.OBJ
 B   $6800  [No Date]           4096     4608 *FONT.EAGLE
 B   $5800  [No Date]             46      512 *MOVE FONT.OBJ
 B   $9000  [No Date]           1024     1536 *EAGLE1.DTA
 B   $0803  [No Date]           4013     4352 *RUNTIME
 B   $999B  [No Date]           4524     5120 *D.OBJ
 B   $999B  [No Date]           6137     6400 *C.OBJ
 B   $D000  [No Date]            330      768 *SIDTRANC.OBJ3
 B   $999B  [No Date]           2510     3584 *A.OBJ
 B   $6000  [No Date]            768     1280 *SOLO3.FNT
 B   $0200  [No Date]            195      512 *AS
 B   $4000  [No Date]           8184     8704 *TITLE1
 B   $4000  [No Date]           8184     8448 *TITLE2
 B   $5000  [No Date]           1074     1536 *SCN.DTA
```

**Comment by peterferrie** [comment]
I edited the constant in Copy II+ to extract the files. :-)
The key is "let me specify". i.e., if CiderPress had the catalog track as a variable, with a UI element that could change it, that would be ideal.
I've never used the "Confirm disk image format" option.  I did not even notice it before.  I will try things.

**Comment by fadden** [comment]
Using tip-of-tree CiderPress II:
```
$ cp2 v F-15\ Strike\ Eagle.nib
File: F-15 Strike Eagle.nib
Unable to recognize disk image contents

$ cp2 v --set-int=dos-vtoc-track:0x15 F-15\ Strike\ Eagle.nib
File: F-15 Strike Eagle.nib
Disk image (Nibble525, codec=Std 16-sector) - 140KB DOS 3.3 Vol 254, 147 sectors free
Type Auxtyp Modified          Length  Storage *Name
---- ------ --------------- -------- -------- ----------------------------------
 B   $0300  [No Date]            206      512 *SIDTRANC.OBJ0
 B   $7800  [No Date]            480      768 *DASH0.MAP
 [...]
```

So you can now:
```
$ cp2 extract --preserve=naps --set-int=dos-vtoc-track:0x15 F-15\ Strike\ Eagle.nib
extracting SIDTRANC.OBJ0 -> SIDTRANC.OBJ0#060300
extracting DASH0.MAP -> DASH0.MAP#067800
extracting DASH1.MAP -> DASH1.MAP#065208
 [...]
```
Add `--raw` to ignore the DOS file types and grab full sectors (just remember to specify it when adding as well).

Direct disk-to-disk DOS copies won't work, because the setting simply overrides the default VTOC value.  On the other hand, it works when formatting, so you can create your very own obfuscated disks with `cp2 cdi --set-int=dos-vtoc-track:0x15 foo.do 140k dos`.

The CLI is usable, GUI will have to wait for another day.  I probably won't update the original CiderPress because I haven't fiddled with MFC in 20 years.

**Comment by peterferrie** [comment]
> Using tip-of-tree CiderPress II:
> ...
>
> So you can now:
> ```
> $ cp2 extract --preserve=naps --set-int=dos-vtoc-track:0x15 F-15\ Strike\
> Eagle.nib
> extracting SIDTRANC.OBJ0 -> SIDTRANC.OBJ0#060300
> extracting DASH0.MAP -> DASH0.MAP#067800
> extracting DASH1.MAP -> DASH1.MAP#065208
>  [...]

Oh, that's super.

> Add `--raw` to ignore the DOS file types and grab full sectors (just
> remember to specify it when adding as well).

That's a nice feature that I did not even consider.

> Direct disk-to-disk DOS copies won't work, because the setting simply
> overrides the default VTOC value.  On the other hand, it works when
> formatting, so you can create your very own obfuscated disks with `cp2 cdi
> --set-int=dos-vtoc-track:0x15 foo.do 140k dos`.

Ha, I don't need that part. :-)

> The CLI is usable, GUI will have to wait for another day.  I probably won't
> update the original CiderPress because I haven't fiddled with MFC in 20
> years.

That's fine, too.  CLI is okay for me.
Thanks!
