### ISSUE TITLE
Merlin formatting introduces erroneous spaces

### ISSUE THREAD

**Issue by roughana** [fadden/ciderpress#9]
Merlin source formatting and exporting introduces spaces before ';' within macro parameters.
This causes failures when trying to assemble the files in Merlin32.

For example:
'Converted Text' view of a partial Merlin source file (This is fine - no additional white space)

```
~PPToPort #:LOCINFO;#:SRCRECT;#0;#0;#0
~EndUpdate WINDPORT
 PLD
 PLB
 RTL

:LOCINFO DA $80
:PICPTR ADRL 0
 DA $A0
:SRCRECT RECTAT 0;0;200;640
```

'Merlin Assembler' view of Merlin source file - Notice additional white spaces on the indicated lines

    ~PPToPort #:LOCINFO ;#:SRCRECT;#0;#0;#0    <-----
    ~EndUpdate WINDPORT
        PLD
        PLB
        RTL

    :LOCINFO DA $80
    :PICPTR ADRL 0
        DA $A0
    :SRCRECT RECTAT 0 ;0;200;640 <-----

When exporting the files using the Auto-detect & convert file with Tex option, the additional spaces are also being introduced.

Merlin 32 treats the rest of the line as a comment instead of as parameters for the macro.
I believe Merlin 16 would as well.

Rule: Never introduce a space into the line if there is not already a space.

**Comment by roughana** [comment]
There does not appear to be a workaround because conversion needs to be performed to strip high bits, and the text file conversion options all have the same result.

**Comment by fadden** [comment]
I think this:

        } else if (*srcPtr == 0xbb) {       // high-ASCII ';'
            // just comment, or comment on mnemonic w/o operand
            // (shouldn't tab out if line started with label but
            // contains 0x20s instead of 0xa0s between components;
            // oh well.)
            state = kStateComment;
            OutputTab(tabStop[state]);
            Output(*srcPtr & 0x7f);

needs to be looking for a preceding space.

Workaround: Edit -> Preferences -> File Viewer, uncheck "Assembly source". That should do the general text conversion without the Merlin 8 handling.

**Comment by fadden** [comment]
Can you send me a disk image with test files?

**Comment by roughana** [comment]
I can confirm that the workaround does work, although there is no whitespace padding.
I have provided a testcase archive with 3 example lines via email.

**Comment by fadden** [comment]
I've uploaded a possible fix: https://github.com/fadden/ciderpress/releases/tag/4.0.1-a2

**Comment by roughana** [comment]
Thank you. That worked fine for me.
When I extract Testcase.S (dialog initially configured for ease of use in Windows) with 'Add type extension' unticked,why is .TXT added to filename?

Regards,Andrew

**Comment by fadden** [comment]
That's the intended behavior.

Looking at the code, it works this way because the file reformatters overrule the file extraction naming behavior.  The output format, which could be text, RTF, BMP, or CSV, is determined by the reformatter.  In theory, a BAS file could be either text or RTF, depending on whether or not syntax highlighting is added, so it must depend on the actual conversion.

In most cases it would be less useful, and possibly misleading, to convert an extracted file and not give it a type extension that indicates the contents have been converted.  "Add type extension" is intended for files that are already in a usable form, such as text (just needs line conversion) or .PO (can be extracted and opened with CiderPress), but need a Windows type extension to replace the file/aux type information that is being lost.  The format conversion not only forces a type extension, it also nullifies the "add file attribute preservation" option, because CiderPress doesn't know how to convert files back the other way -- so having type preservation tags in filenames might give you the wrong impression about the file contents.

The current behavior is not necessarily what you'd expect, but I'm not entirely comfortable changing it.  One of my goals was that you could extract a hard drive's contents to Windows with the "configure to preserve" options, add the files to a different disk image, and then boot that image on a IIgs, so anything that potentially confuses people about the preserved-ness of a file makes me nervous.

https://github.com/fadden/ciderpress/blob/master/app/Actions.cpp#L873

**Comment by roughana** [comment]
Is there a way to convert Merlin source files and have the filename remain the same?
If not, I will raise a feature request.

Thanks
Andrew

**Comment by fadden** [comment]
Nope.  Please raise. :-)

**Comment by roughana** [comment]
done
